drop table if exists genres cascade;
create table if not exists genres
(
    id   int generated by default as identity primary key,
    name varchar(25) not null
);

drop table if exists films cascade;
create table if not exists films
(
    id           int generated by default as identity primary key,
    name         varchar(50) not null,
    description  varchar(200),
    release_date date not null,
    duration     int not null
);